# Creation of configmap 1
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: logging
  labels:
    app: fluent-bit
data:
  ClusterName: dev-ai-common
  RegionName: us-west-2
  FluentBitHttpPort: "2020"
  FluentBitReadFromHead: "OFF"
  logs.region: us-west-2
  cluster.name: dev-ai-common
  http.server: "ON"
  http.port: "2020"
  read.head: "OFF"
  read.tail: "ON"