# Creation of the kubernetes service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
  annotations:
    #eks.amazonaws.com/role-arn: arn:aws:iam::439603311558:role/eksctl-dev-ai-common-addon-iamserviceaccount--Role1-NKhbZGC8O7Zj
    #eks.amazonaws.com/role-arn: arn:aws:iam::439603311558:role/eksctl-dev-ai-common-addon-iamserviceaccount--Role1-vW7Tare650I3
    eks.amazonaws.com/role-arn: arn:aws:iam::439603311558:role/eksctl-dev-ai-common-addon-iamserviceaccount--Role1-oMbm7g3KoQMg
